#! /usr/bin/env php 
<?php

use Symfony\Component\Console\Application;
use MeuApp\{
    ExibirCommand,
    NovaCommand
};
use MeuApp\Database;


require "vendor/autoload.php";

$app = new Application("meu app demo", "1.0");

try {
    $pdo = new \PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

} catch(PDOException $e) {
    echo "Não foi possivel se conectar com o banco de dados.";
    die(1);
}

$database = new Database($pdo);

$app->add(new ExibirCommand($database));
$app->add(new NovaCommand($database));
    
$app->run();




